
# https://github.com/nodejs/docker-node/blob/master/10/alpine/Dockerfile
# https://github.com/docker-library/golang/blob/master/1.12/alpine3.9/Dockerfile

FROM golang:1.12.3-alpine as golang_builder

FROM node:10.15.3-alpine as node_builder

FROM alpine:3.9

ENV GOLANG_VERSION 1.12.3

# COPY --from=builder target/*.jar app.jar

# for golang




